### PR TITLE
DDF-2392 Fixes issue replacing paths in config.ldif on Windows.

### PR DESCRIPTION
**Pull request by coyotesqrl**
Also updates the source/target to Java 1.8 as we are using 1.8 features.

We'll want to cut a 1.3.3 release pretty quickly I think.

This should be tested on Windows to hero.

@stustison @jaymcnallie @shaundmorris @Lambeaux

### CODE REVIEW

**Comment by shaundmorris** [comment]
👍

**Comment by jlcsmith** [comment]
👍

**Comment by stustison** [comment]
👍

**Comment by Lambeaux** [comment]
Little late to the party, but double-verified build on Windows.

**Pull request merged**
