### PR TITLE
LDAP-1: Upgraded OpenDJ to 2.6.2

### PR DESCRIPTION
**Pull request by AzGoalie**
Upgraded OpenDJ from 2.4.6 to 2.6.2. Most of the file changes are from the formatting that intellij did. The OpenDJ upgrade command changed all the ldiff files. The main files I changed are the pom files to update the version to 1.3.0-SNAPSHOT and LDAPManager to add/change a few variables and copy over the buildinfo file in the copyDefaultFiles method.

@shaundmorris 
@mrmateo

[Review on Reviewable](https://reviewable.io/reviews/codice/opendj-osgi/6)

### CODE REVIEW

**Comment by shaundmorris** [comment]
Built and Tested everything. Looks like primarily configuration file (e.g. LDIF changes) :+1: 

---

Review status: all files reviewed, 1 unresolved discussion, some commit checks pending.
Reviewed files:
- embedded/opendj-embedded-app/pom.xml @ r1
- embedded/opendj-embedded-app/src/main/resources/features.xml @ r1
- embedded/opendj-embedded-server/pom.xml @ r1
- embedded/opendj-embedded-server/src/main/java/org/codice/opendj/embedded/server/LDAPException.java @ r1
- embedded/opendj-embedded-server/src/main/java/org/codice/opendj/embedded/server/LDAPManager.java @ r1
- embedded/opendj-embedded-server/src/main/resources/config/buildinfo @ r1
- embedded/opendj-embedded-server/src/main/resources/config/config.ldif @ r1
- embedded/opendj-embedded-server/src/main/resources/config/http-config.json @ r1
- embedded/opendj-embedded-server/src/main/resources/config/schema/00-core.ldif @ r1
- embedded/opendj-embedded-server/src/main/resources/config/schema/02-config.ldif @ r1
- embedded/opendj-embedded-server/src/main/resources/config/upgrade/schema.ldif.8102 @ r1
- embedded/opendj-embedded-server/src/main/resources/config/upgrade/schema.ldif.9086 @ r1
- embedded/opendj-embedded-server/src/main/resources/OSGI-INF/blueprint/blueprint.xml @ r1
- embedded/opendj-embedded-server/src/main/resources/OSGI-INF/metatype/metatype.xml @ r1
- embedded/opendj-embedded-server/src/test/java/org/codice/opendj/embedded/server/LDAPManagerTest.java @ r1
- embedded/pom.xml @ r1
- pom.xml @ r1

---

<sup>**[embedded/opendj-embedded-server/src/main/java/org/codice/opendj/embedded/server/LDAPManager.java, line 66 \[r1\]](https://reviewable.io:443/reviews/codice/opendj-osgi/6#-JrZSvAjqqmU6LS6oT3s)** ([raw file](https://github.com/codice/opendj-osgi/blob/5d3c93b99f4584af22d6816d1c8e86c1f8c1e172/embedded/opendj-embedded-server/src/main/java/org/codice/opendj/embedded/server/LDAPManager.java#L66)):</sup>
Okay we needed a new LDIF schema...

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/opendj-osgi/6)

**Comment by AzGoalie** [comment]
Review status: all files reviewed, 1 unresolved discussion, some commit checks pending.

---

<sup>**[embedded/opendj-embedded-server/src/main/java/org/codice/opendj/embedded/server/LDAPManager.java, line 66 \[r1\]](https://reviewable.io:443/reviews/codice/opendj-osgi/6#-JrZSvAjqqmU6LS6oT3s)** ([raw file](https://github.com/codice/opendj-osgi/blob/5d3c93b99f4584af22d6816d1c8e86c1f8c1e172/embedded/opendj-embedded-server/src/main/java/org/codice/opendj/embedded/server/LDAPManager.java#L66)):</sup>
To get the proper schema version we need the full 2.6.2 zip of OpenDJ. The upgrade command created this file.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/opendj-osgi/6)

**Comment by stustison** [comment]
I did not try to modify keystores, but I did build and run. It appears to work and I can log in as an LDAP user in DDF.

**Comment by shaundmorris** [comment]
Verified final build due to parameterized logging change. @mrmateo if you get a chance would appreciate any feedback.  @stustison and I have tested it.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/opendj-osgi/6)

**Comment by mrmateo** [comment]
Sorry for the late response @AzGoalie , I looked at the code when you created the PR but forgot to comment. Tested it out and it worked for me. When I created the initial upgrade ticket these were the files I assumed would need to be updated.

Thanks!

**Pull request merged**
